-- SELECT * FROM people1 ORDER BY pid LIMIT 10 OFFSET 20;
SELECT * FROM people1 ORDER BY pid FETCH FIRST 10 ROWS ONLY;
SELECT * FROM people1 ORDER BY pid OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;
SELECT * FROM people1 ORDER BY PID OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY;